//
//  HamuWord.swift
//
//
//  Created by hidemune on 3/30/24.
//

import Foundation

public enum HamuWord: String, CaseIterable {
    case アウチッチ
    case あかいトーン
    case あたっちゅ
    case あちゅちゅ
    case あとチョッチ
    case あわせっち
    case イエーっちゅ
    case ウ～ラ～ラ～
    case うぇいきゅー
    case うちゃー
    case うにに～
    case うりり～
    case うれぴっプル
    case おぞぞ～
    case オフるん
    case おめでっちゅ
    case おもろぷぅ
    case がくちゅ
    case かしかし
    case がちゃちゃ
    case がちゅん
    case がっちリン
    case かなデ～ル
    case ガリっちょ
    case かわルンバ
    case がんばリン
    case キョロリン
    case クイッちゅ
    case くりっくり
    case クリんパ
    case ぐるマーニ
    case くるリン
    case グレイちゅ
    case ぐれえてる
    case クレレッ
    case くんかくんか
    case ゲチュー
    case げんまる
    case こそそ
    case こまっち
    case サンちゅ
    case しーちゅる
    case シビビーン
    case じめるるん
    case しょーなっち
    case しんパイン
    case すかぴー
    case セサミん
    case ターゲッちゅ
    case ダイジョッピ
    case たのモッちぃ
    case ちーぷる
    case ぢぢぢぃ～
    case ちぴっと
    case ちゃいっ
    case ちゅきリーナ
    case ちゅ～ラブー
    case ちょびりんき
    case つっつん
    case デアデア～ん
    case デリちゅ
    case てれらん
    case でろろん
    case デンデン
    case どすこイッチ
    case どっかり
    case ともち
    case ドンチャカ
    case ナイ～ん
    case ねがちゅる
    case ノッくん
    case のぼちゅ
    case のるるン
    case のんたる
    case パーへくち
    case ばいきゅー
    case ばくドキ
    case パチっと
    case はなマルっち
    case ぱぱらーん
    case はむはー
    case ぱる
    case バルっち
    case バレりっち
    case ピーちゅ
    case ひえビッチ
    case ピカッシュ
    case ぴくぴ
    case ひそそ
    case ピピンッ
    case びゅ～りっホ
    case びろろーん
    case プキキ
    case ブグブグ
    case ぷっぷく
    case ふに～
    case フラランちゅ
    case ぶらりんちょ
    case ぷりちゅ～
    case フリリッくる
    case プレーぜる
    case ぶれぶー
    case ペコすきー
    case べそきゅー
    case ぺちゃちゃ
    case ポイっちょ
    case ポケらん
    case ポチっと
    case ぼっち
    case ポンぽポン
    case まいちー
    case マジフル
    case まっちゅる
    case まもっち
    case みちゅてる
    case むちゅちゅ
    case むっほっほ
    case めざちゅルン
    case めちゅ～っ
    case もぐちゅ
    case もっちょ
    case もひもひ
    case やーノン
    case やほほーい
    case よっちー
    case ラッピィ～
    case るんピカ
    case わささ
    case わたた
    case ワワワワ～
    case ワンダちゅ
    
    func getHamuWord() -> String {
        switch self {
        case .アウチッチ:
            return "アウチッチ"
        case .あかいトーン:
            return "あかいトーン"
        case .あたっちゅ:
            return "あたっちゅ"
        case .あちゅちゅ:
            return "あちゅちゅ"
        case .あとチョッチ:
            return "あとチョッチ"
        case .あわせっち:
            return "あわせっち"
        case .イエーっちゅ:
            return "イエーっちゅ"
        case .ウ～ラ～ラ～:
            return "ウ～ラ～ラ～"
        case .うぇいきゅー:
            return "うぇいきゅー"
        case .うちゃー:
            return "うちゃー"
        case .うにに～:
            return "うにに～"
        case .うりり～:
            return "うりり～"
        case .うれぴっプル:
            return "うれぴっプル"
        case .おぞぞ～:
            return "おぞぞ～"
        case .オフるん:
            return "オフるん"
        case .おめでっちゅ:
            return "おめでっちゅ"
        case .おもろぷぅ:
            return "おもろぷぅ"
        case .がくちゅ:
            return "がくちゅ"
        case .かしかし:
            return "かしかし"
        case .がちゃちゃ:
            return "がちゃちゃ"
        case .がちゅん:
            return "がちゅん"
        case .がっちリン:
            return "がっちリン"
        case .かなデ～ル:
            return "かなデ～ル"
        case .ガリっちょ:
            return "ガリっちょ"
        case .かわルンバ:
            return "かわルンバ"
        case .がんばリン:
            return "がんばリン"
        case .キョロリン:
            return "キョロリン"
        case .クイッちゅ:
            return "クイッちゅ"
        case .くりっくり:
            return "くりっくり"
        case .クリんパ:
            return "クリんパ"
        case .ぐるマーニ:
            return "ぐるマーニ"
        case .くるリン:
            return "くるリン"
        case .グレイちゅ:
            return "グレイちゅ"
        case .ぐれえてる:
            return "ぐれえてる"
        case .クレレッ:
            return "クレレッ"
        case .くんかくんか:
            return "くんかくんか"
        case .ゲチュー:
            return "ゲチュー"
        case .げんまる:
            return "げんまる"
        case .こそそ:
            return "こそそ"
        case .こまっち:
            return "こまっち"
        case .サンちゅ:
            return "サンちゅ"
        case .しーちゅる:
            return "しーちゅる"
        case .シビビーン:
            return "シビビーン"
        case .じめるるん:
            return "じめるるん"
        case .しょーなっち:
            return "しょーなっち"
        case .しんパイン:
            return "しんパイン"
        case .すかぴー:
            return "すかぴー"
        case .セサミん:
            return "セサミん"
        case .ターゲッちゅ:
            return "ターゲッちゅ"
        case .ダイジョッピ:
            return "ダイジョッピ"
        case .たのモッちぃ:
            return "たのモッちぃ"
        case .ちーぷる:
            return "ちーぷる"
        case .ぢぢぢぃ～:
            return "ぢぢぢぃ～"
        case .ちぴっと:
            return "ちぴっと"
        case .ちゃいっ:
            return "ちゃいっ"
        case .ちゅきリーナ:
            return "ちゅきリーナ"
        case .ちゅ～ラブー:
            return "ちゅ～ラブー"
        case .ちょびりんき:
            return "ちょびりんき"
        case .つっつん:
            return "つっつん"
        case .デアデア～ん:
            return "デアデア～ん"
        case .デリちゅ:
            return "デリちゅ"
        case .てれらん:
            return "てれらん"
        case .でろろん:
            return "でろろん"
        case .デンデン:
            return "デンデン"
        case .どすこイッチ:
            return "どすこイッチ"
        case .どっかり:
            return "どっかり"
        case .ともち:
            return "ともち"
        case .ドンチャカ:
            return "ドンチャカ"
        case .ナイ～ん:
            return "ナイ～ん"
        case .ねがちゅる:
            return "ねがちゅる"
        case .ノッくん:
            return "ノッくん"
        case .のぼちゅ:
            return "のぼちゅ"
        case .のるるン:
            return "のるるン"
        case .のんたる:
            return "のんたる"
        case .パーへくち:
            return "パーへくち"
        case .ばいきゅー:
            return "ばいきゅー"
        case .ばくドキ:
            return "ばくドキ"
        case .パチっと:
            return "パチっと"
        case .はなマルっち:
            return "はなマルっち"
        case .ぱぱらーん:
            return "ぱぱらーん"
        case .はむはー:
            return "はむはー"
        case .ぱる:
            return "ぱる"
        case .バルっち:
            return "バルっち"
        case .バレりっち:
            return "バレりっち"
        case .ピーちゅ:
            return "ピーちゅ"
        case .ひえビッチ:
            return "ひえビッチ"
        case .ピカッシュ:
            return "ピカッシュ"
        case .ぴくぴ:
            return "ぴくぴ"
        case .ひそそ:
            return "ひそそ"
        case .ピピンッ:
            return "ピピンッ"
        case .びゅ～りっホ:
            return "びゅ～りっホ"
        case .びろろーん:
            return "びろろーん"
        case .プキキ:
            return "プキキ"
        case .ブグブグ:
            return "ブグブグ"
        case .ぷっぷく:
            return "ぷっぷく"
        case .ふに～:
            return "ふに～"
        case .フラランちゅ:
            return "フラランちゅ"
        case .ぶらりんちょ:
            return "ぶらりんちょ"
        case .ぷりちゅ～:
            return "ぷりちゅ～"
        case .フリリッくる:
            return "フリリッくる"
        case .プレーぜる:
            return "プレーぜる"
        case .ぶれぶー:
            return "ぶれぶー"
        case .ペコすきー:
            return "ペコすきー"
        case .べそきゅー:
            return "べそきゅー"
        case .ぺちゃちゃ:
            return "ぺちゃちゃ"
        case .ポイっちょ:
            return "ポイっちょ"
        case .ポケらん:
            return "ポケらん"
        case .ポチっと:
            return "ポチっと"
        case .ぼっち:
            return "ぼっち"
        case .ポンぽポン:
            return "ポンぽポン"
        case .まいちー:
            return "まいちー"
        case .マジフル:
            return "マジフル"
        case .まっちゅる:
            return "まっちゅる"
        case .まもっち:
            return "まもっち"
        case .みちゅてる:
            return "みちゅてる"
        case .むちゅちゅ:
            return "むちゅちゅ"
        case .むっほっほ:
            return "むっほっほ"
        case .めざちゅルン:
            return "めざちゅルン"
        case .めちゅ～っ:
            return "めちゅ～っ"
        case .もぐちゅ:
            return "もぐちゅ"
        case .もっちょ:
            return "もっちょ"
        case .もひもひ:
            return "もひもひ"
        case .やーノン:
            return "やーノン"
        case .やほほーい:
            return "やほほーい"
        case .よっちー:
            return "よっちー"
        case .ラッピィ～:
            return "ラッピィ～"
        case .るんピカ:
            return "るんピカ"
        case .わささ:
            return "わささ"
        case .わたた:
            return "わたた"
        case .ワワワワ～:
            return "ワワワワ～"
        case .ワンダちゅ:
            return "ワンダちゅ"
        }
    }
    
    func getNaturalWord() -> String {
        switch self {
        case .アウチッチ:
            return "痛い"
        case .あかいトーン:
            return "絆"
        case .あたっちゅ:
            return "体当たり"
        case .あちゅちゅ:
            return "暑い"
        case .あとチョッチ:
            return "惜しい"
        case .あわせっち:
            return "協力する"
        case .イエーっちゅ:
            return "はい"
        case .ウ～ラ～ラ～:
            return "幸せ"
        case .うぇいきゅー:
            return "待つ"
        case .うちゃー:
            return "反省"
        case .うにに～:
            return "イケてな～い"
        case .うりり～:
            return "売る"
        case .うれぴっプル:
            return "嬉しい"
        case .おぞぞ～:
            return "恐ろしい"
        case .オフるん:
            return "外す"
        case .おめでっちゅ:
            return "おめでとう"
        case .おもろぷぅ:
            return "おもしろい"
        case .がくちゅ:
            return "学習"
        case .かしかし:
            return "かじる"
        case .がちゃちゃ:
            return "うるさい"
        case .がちゅん:
            return "ショック"
        case .がっちリン:
            return "かたい"
        case .かなデ～ル:
            return "演奏する"
        case .ガリっちょ:
            return "ひっかく"
        case .かわルンバ:
            return "かわる"
        case .がんばリン:
            return "がんばれっ"
        case .キョロリン:
            return "見る"
        case .クイッちゅ:
            return "急ぐ"
        case .くりっくり:
            return "そっくり"
        case .クリんパ:
            return "掃除"
        case .ぐるマーニ:
            return "肩車"
        case .くるリン:
            return "回る"
        case .グレイちゅ:
            return "すごい"
        case .ぐれえてる:
            return "悪い子"
        case .クレレッ:
            return "ちょうだい"
        case .くんかくんか:
            return "においを嗅ぐ"
        case .ゲチュー:
            return "手に入れる"
        case .げんまる:
            return "約束"
        case .こそそ:
            return "隠れる"
        case .こまっち:
            return "困る"
        case .サンちゅ:
            return "ありがとう"
        case .しーちゅる:
            return "透けている"
        case .シビビーン:
            return "痺れる"
        case .じめるるん:
            return "湿っている"
        case .しょーなっち:
            return "仕方がない"
        case .しんパイン:
            return "心配する"
        case .すかぴー:
            return "寝る"
        case .セサミん:
            return "開く"
        case .ターゲッちゅ:
            return "狙う"
        case .ダイジョッピ:
            return "大丈夫"
        case .たのモッちぃ:
            return "頼もしい"
        case .ちーぷる:
            return "トイレ"
        case .ぢぢぢぃ～:
            return "嫌い"
        case .ちぴっと:
            return "小さい"
        case .ちゃいっ:
            return "ごめんなさい"
        case .ちゅきリーナ:
            return "好き"
        case .ちゅ～ラブー:
            return "愛している"
        case .ちょびりんき:
            return "イケてる～"
        case .つっつん:
            return "突っつく"
        case .デアデア～ん:
            return "大切"
        case .デリちゅ:
            return "美味しい"
        case .てれらん:
            return "恥ずかしい"
        case .でろろん:
            return "疲れる"
        case .デンデン:
            return "伝える"
        case .どすこイッチ:
            return "押す"
        case .どっかり:
            return "大きい"
        case .ともち:
            return "友達"
        case .ドンチャカ:
            return "盛り上がる"
        case .ナイ～ん:
            return "失う"
        case .ねがちゅる:
            return "お願い"
        case .ノッくん:
            return "叩く"
        case .のぼちゅ:
            return "登る"
        case .のるるン:
            return "乗る"
        case .のんたる:
            return "ゆっくり"
        case .パーへくち:
            return "完璧"
        case .ばいきゅー:
            return "さようなら"
        case .ばくドキ:
            return "驚く"
        case .パチっと:
            return "目覚める"
        case .はなマルっち:
            return "100点！"
        case .ぱぱらーん:
            return "見せる"
        case .はむはー:
            return "あいさつ"
        case .ぱる:
            return "引っ張る"
        case .バルっち:
            return "ライバル"
        case .バレりっち:
            return "バレる"
        case .ピーちゅ:
            return "平和"
        case .ひえビッチ:
            return "寒い"
        case .ピカッシュ:
            return "磨く"
        case .ぴくぴ:
            return "聞こえる"
        case .ひそそ:
            return "内緒"
        case .ピピンッ:
            return "気が付く"
        case .びゅ～りっホ:
            return "綺麗"
        case .びろろーん:
            return "広い"
        case .プキキ:
            return "笑う"
        case .ブグブグ:
            return "深い"
        case .ぷっぷく:
            return "持ち運ぶ"
        case .ふに～:
            return "優しい"
        case .フラランちゅ:
            return "フラフラする"
        case .ぶらりんちょ:
            return "ぶら下がる"
        case .ぷりちゅ～:
            return "かわいい"
        case .フリリッくる:
            return "自由"
        case .プレーぜる:
            return "プレゼント"
        case .ぶれぶー:
            return "勇気"
        case .ペコすきー:
            return "お腹の空いた"
        case .べそきゅー:
            return "悲しい"
        case .ぺちゃちゃ:
            return "おしゃべり"
        case .ポイっちょ:
            return "あきらめる"
        case .ポケらん:
            return "忘れる"
        case .ポチっと:
            return "取り付ける"
        case .ぼっち:
            return "お前ら"
        case .ポンぽポン:
            return "おなかいっぱい"
        case .まいちー:
            return "どんまい"
        case .マジフル:
            return "ホント"
        case .まっちゅる:
            return "力持ち"
        case .まもっち:
            return "守る"
        case .みちゅてる:
            return "不思議"
        case .むちゅちゅ:
            return "遊ぶ"
        case .むっほっほ:
            return "強い"
        case .めざちゅルン:
            return "目標"
        case .めちゅ～っ:
            return "怒る"
        case .もぐちゅ:
            return "潜る"
        case .もっちょ:
            return "アンコール"
        case .もひもひ:
            return "食べる"
        case .やーノン:
            return "いいえ"
        case .やほほーい:
            return "呼ぶ"
        case .よっちー:
            return "仲良し"
        case .ラッピィ～:
            return "幸運"
        case .るんピカ:
            return "おしゃれ"
        case .わささ:
            return "たくさん"
        case .わたた:
            return "慌てる"
        case .ワワワワ～:
            return "歌う"
        case .ワンダちゅ:
            return "素敵"
        }
    }
}
